server {
    listen 80;
    server_name cynthiawong.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cynthiawong.duckdns.org;

    location / {
        proxy_pass http://myportfolio:5000/;
    }

    # load cert files
    ssl_certificate /etc/letsencrypt/live/cynthiawong.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cynthiawong.duckdns.org/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/cynthiawong.duckdns.org/chain.pem;
}

