name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # trigger adds a "Run workflow" button, have to check if not outdated

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps: # create a file called ~/.ssh/deploy-key.pem which contains the SSH_PRIVATE_KEY secret
    # set correct permission chmod 600 for file
    # create a config file in /home/runner/.ssh/ (Github spins up own fresh, temp VM in the cloud for every workflow run and deletes this VM after workflow run). The SSH config temporarily exists. In this file, added a host directive named "my-vm" and all the ssh options underneath including HostName, User, Identity File. This allows us to just use "ssh my-vps" to connect to the droplet instead of full ssh command "ssh root@<ip> -i ~/.ssh/deploy-key.pem -o StrictHostKeyChecking=no".
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem 
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }} # add secrets to Github
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
        
      - name: Print project root dir # connect to droplet using command "ssh my-vps" and executes 'cd ${{ secrets.PROJECT_ROOT}} && pwd'. This cd into our proj root dir and runs pwd to print out the dir.
        run: ssh my-vps 'cd ${{ secrets.PROJECT_ROOT }} && pwd'

